### ISSUE TITLE
LrSlide fails to make a slide

### ISSUE THREAD

**Issue by TerryHewitt** [DaveBurns/LrSlide#1]
Just installed LrSlide from GitHub onto Windos10 running Lightroom Classic 9.3.

Chrome.exe in the standard place

When I run it it fails to create a slide.
This is the contents of the log files I could find.

CONTENTS OF DEBUG.LOG

20/08/03 20:16:20 com.daveburnsphoto.lightroom.LrSlide	TRACE	********* LrSlide BOOTSTRAP ************
20/08/03 20:16:20 com.daveburnsphoto.lightroom.LrSlide	TRACE	********* LrSlide MAIN. Mode: add
20/08/03 20:16:20 com.daveburnsphoto.lightroom.LrSlide	TRACE	{--table: 1
    chromePath = "", 
    slideHeight = "1200", 
    slideWidth = "1600"}
20/08/03 20:16:20 com.daveburnsphoto.lightroom.LrSlide	TRACE	Path based on existing selected photo: D:\Users\hewitt\Documents\AAA-WTH\Danielle\Helen\LrSlide.jpg
20/08/03 20:16:20 com.daveburnsphoto.lightroom.LrSlide	TRACE	Getting string from cache file:  fontCache.txt
20/08/03 20:16:25 com.daveburnsphoto.lightroom.LrSlide	TRACE	dialog results: ok
20/08/03 20:16:25 com.daveburnsphoto.lightroom.LrSlide	TRACE	Rendering slide in D:\Users\hewitt\Documents\AAA-WTH\Danielle\Helen\LrSlide.jpg
20/08/03 20:16:25 com.daveburnsphoto.lightroom.LrSlide	TRACE	Running Chrome Unknown version C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
20/08/03 20:16:25 com.daveburnsphoto.lightroom.LrSlide	TRACE	{--table: 1
    [1] = "--headless", 
    [2] = "--disable-gpu", 
    [3] = "--hide-scrollbars", 
    [4] = "--crash-dumps-dir=/tmp", 
    [5] = "--screenshot=\"D:\\Users\\hewitt\\Documents\\AAA-WTH\\Danielle\\Helen\\LrSlide.jpg\"", 
    [6] = "--window-size=1600,1200", 
    [7] = "file://C:\\Users\\hewitt\\AppData\\Local\\Temp\\LrSlide-tempHTML-14.html"}
20/08/03 20:16:25 com.daveburnsphoto.lightroom.LrSlide	TRACE	command line: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --headless --disable-gpu --hide-scrollbars --crash-dumps-dir=/tmp --screenshot="D:\Users\hewitt\Documents\AAA-WTH\Danielle\Helen\LrSlide.jpg" --window-size=1600,1200 file://C:\Users\hewitt\AppData\Local\Temp\LrSlide-tempHTML-14.html > C:\Users\hewitt\AppData\Local\Temp\stdoutTemp-18.txt 2> C:\Users\hewitt\AppData\Local\Temp\stderrTemp-18.txt
20/08/03 20:16:26 com.daveburnsphoto.lightroom.LrSlide	TRACE	result: 1
20/08/03 20:16:26 com.daveburnsphoto.lightroom.LrSlide	TRACE	ERROR. Failed to run Chrome. Result code: 1
20/08/03 20:16:26 com.daveburnsphoto.lightroom.LrSlide	TRACE	"STDERR:" {--table: 1
    [1] = "'C:\\Program' is not recognized as an internal or external command,", 
    [2] = "operable program or batch file."}

CONTENTS OF :\Users\hewitt\AppData\Local\Temp\stderrTemp-18.txt

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

CONTENTS OF :\Users\hewitt\AppData\Local\Temp\stdoutTemp-18.txt

FILE is 0KB and EMPTY

If I cut and paste the command line to cmd terminal it sort of works
stderrTemp-18.txt contains
[0803/203425.185:INFO:headless_shell.cc(615)] Written to file D:\Users\hewitt\Documents\AAA-WTH\Danielle\Helen\LrSlide.jpg.
[0803/203425.910:ERROR:process_info.cc(375)] NtQuerySystemInformation SystemExtendedHandleInformation: The specified information record length does not match the length required for the specified information class. (0xc0000004)

And the LrSlide.jpg is created.

Please advise a correction.
Best wishes
Terry

**Comment by TerryHewitt** [comment]
Further Investigation. It seems to work when there are NO spaces in the screenshot filename.
So " are needed arround such filenames
So in Chrome.lua I changed
 table.insert( args, '--screenshot=' .. outputFilename )
TO

 table.insert( args, '--screenshot=' .. '"' .. outputFilename ..'"')

and in UTIL.LUA in function Util.execAndCapture( cmdLine, options )


I changed this 
	result = Util.exec( cmdLine )

to this
 cmdLine = '"' .. cmdLine ..'"'
	result = Util.exec( cmdLine )

It now appears to be working!
However still getting the messages in stderrTemp-xx.txt

Best wishes
Terry

**Comment by DaveBurns** [comment]
Terry - It looks like the screenshot's file name itself was fine but the program's path is not being quoted. I'm thinking the only fix you need is the one you made in util.lua. I'll have to investigate though because there should be code there already to handle this exact situation.

Glad you got things working in the meantime though.

db

**Comment by TerryHewitt** [comment]
Dave

Thanks. I'm thinking about some mods. I'll submit them if they work out.
I'm reading the code at the moment but can't find where the text is stored so that it is available when you click edit slide.
I'll get it eventually but if you can spare a few minutes to tell that would be a great help.

Best wishes
Terry

________________________________

**Comment by TerryHewitt** [comment]
Figured out where the text is stored.

**Comment by DaveBurns** [comment]
Terry - Should we close this? It's supposed to work on Windows and Mac as-is so it still seems worth investigating despite the workaround.

You figured out where the text is stored but for any future searchers, I'll put it here: LrSlide defines a metadata provider in LrSlideMetadataDefinitionFile.lua. To keep it simple, it defines one field: a string. That string happens to be a JSON string. The motivation is to allow for future flexibility of what fields are stored without having to change Lightroom's view of the data. 

That data is read/written in LrSlideMain in the functions readMetadata/writeMetadata. See the functions in that file named getSlideProperties and renderSlide for how the JSON is read and then passed to the renderer. It might be a bit over-engineered for such a simple plugin but at the time I was writing it (10 years ago maybe?) it wasn't clear how far it would go so I tried to keep it general. I'm sure some cleanup is possible.

db

**Comment by TerryHewitt** [comment]
Dave

 

 

Yes, we can close this one, and thanks for the details.

 

Best wishes

 

Terry

 

Professor W T Hewitt

WTH Associates Ltd

 

Telephone: +44 7905 759 003

 

Company registration number:7336226

HMRC VAT Registration number: 998 8457 23

 

Company Registered Address

St George's House  | 215 - 219 Chester Road | Manchester | M15 4JE
